import urllib2, httplib, cookielib
from bs4 import BeautifulSoup

def getcookieopener(path):
    try:
        f = open(path,'r')

        #CookieJar has a subclass called MozillaCookieJar
        #which will load a cookies.txt file, but
        #it can refuse files generated by the Chrome cookies.txt tool,
        #because they sometimes have expiration dates in the form (digits).(digits)
        #and MozillaCookieJar can't deal with the decimal point.
        #This block of code generates a copy of the cookies.txt file
        #with the decimal point in the expiration date stripped out.
        with open(path+'.tmp','w') as tempcookiefile:
            for l in f:
                if l[0] == '#':
                    tempcookiefile.write(l)
                else:    
                    strings = l.split()

                    #Make sure strings has 7 elements.. if missing elements, just add blank strings
                    if len(strings) < 7:
                        while len(strings) < 7:
                            strings.append(' ')
                    for i in range(len(strings)):

                        #Issue caused if the end of line character is '\r'
                        #instead of '\n'
                        if i == 6:
                            if strings[i][-1]=='\r':
                                strings[i] = strings[i][:-1]

                        if i != 4:
                            if i != len(strings)-1:
                                tempcookiefile.write(strings[i]+'\t')
                            else:
                                tempcookiefile.write(strings[i]+'\n')
                        else:
                            s = strings[i].split('.')
                            tempcookiefile.write(s[0]+'\t')

        cj = cookielib.MozillaCookieJar()
        cj.load(path+'.tmp')
        return urllib2.build_opener(urllib2.HTTPCookieProcessor(cj))
        
    except IOError:
        print('IOError')
        return None
